//! `preset-compliance.lock`: the committed record `check` judges. Facts only,
//! no verdicts, no timestamps, no absolute paths, rows sorted, so the same
//! repo state produces the same bytes on every machine.

use crate::model::{Ecosystem, Package};
use anyhow::{Context, Result, bail};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};

pub const FILE_NAME: &str = "preset-compliance.lock";
pub const VERSION: u32 = 1;

const HEADER: &str = "# Generated by `preset-compliance licences scan`. Do not edit by hand.\n\
# Commit it: `preset-compliance licences check` judges this file, without network.\n\n";

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Lock {
    pub version: u32,
    /// Lockfiles found but not scanned, because no adapter exists yet.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub skipped: Vec<Skipped>,
    #[serde(default)]
    pub inputs: Vec<Input>,
    #[serde(default)]
    pub packages: Vec<Package>,
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct Skipped {
    pub path: PathBuf,
    pub ecosystem: Ecosystem,
}

/// A file the facts were derived from, and its hash when they were.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct Input {
    pub path: PathBuf,
    /// Set on lockfiles; manifests have none.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ecosystem: Option<Ecosystem>,
    pub sha256: String,
}

impl Lock {
    pub fn new(
        mut skipped: Vec<Skipped>,
        mut inputs: Vec<Input>,
        mut packages: Vec<Package>,
    ) -> Lock {
        skipped.sort();
        skipped.dedup();
        inputs.sort();
        inputs.dedup();
        packages.sort();
        packages.dedup();
        Lock {
            version: VERSION,
            skipped,
            inputs,
            packages,
        }
    }

    pub fn load(root: &Path) -> Result<Lock> {
        let path = root.join(FILE_NAME);
        let text = std::fs::read_to_string(&path)
            .with_context(|| format!("no {FILE_NAME}; run `preset-compliance licences scan`"))?;
        let lock: Lock =
            toml::from_str(&text).with_context(|| format!("invalid {}", path.display()))?;
        if lock.version != VERSION {
            bail!(
                "{FILE_NAME} is version {}, this build reads version {VERSION}",
                lock.version
            );
        }
        Ok(lock)
    }

    pub fn render(&self) -> Result<String> {
        Ok(format!("{HEADER}{}", toml::to_string(self)?))
    }

    pub fn save(&self, root: &Path) -> Result<()> {
        std::fs::write(root.join(FILE_NAME), self.render()?).context("writing the lock")
    }
}

pub fn hash_file(root: &Path, relative: &Path) -> Result<String> {
    let bytes = std::fs::read(root.join(relative))
        .with_context(|| format!("reading {}", relative.display()))?;
    Ok(Sha256::digest(&bytes)
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Scope, Source};

    fn package(name: &str) -> Package {
        Package {
            ecosystem: Ecosystem::Cargo,
            name: name.into(),
            version: "1.0.0".into(),
            source: Source::Registry,
            declared: Some("MIT".into()),
            scope: Scope::Shipped,
        }
    }

    #[test]
    fn render_is_order_independent_and_round_trips() {
        let a = Lock::new(vec![], vec![], vec![package("b"), package("a")]);
        let b = Lock::new(
            vec![],
            vec![],
            vec![package("a"), package("b"), package("a")],
        );
        assert_eq!(a.render().unwrap(), b.render().unwrap());
        let parsed: Lock = toml::from_str(&a.render().unwrap()).unwrap();
        assert_eq!(parsed, a);
    }
}
